[window]
padding = {x = 15, y = 15}

[font]
normal = { family = "Jetbrains Mono", style = "Regular"}
size = 13

[colors.primary]
foreground = "#d4be98" 
background = "#32302f"

[colors.selection]
text = "#32302f"
background = "#32302f"

[colors.cursor]
cursor = "#a89984"
text = "#32302f"

[colors.normal]
black = "#928374"
red = "#ea6962"
green = "#a9b665"
yellow = "#e78a4e"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"

[colors.bright]
black = "#d4be98"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"
