format = '$python$time-$username-$os-$directory$git_branch$git_status$status[>](bold wite) '

[directory]
format='\[[$path](fg:#a9b665)[$read_only]($read_only_style)\]'
truncate_to_repo = false

[username]
format='\[[$user](fg:#d8a657)\]' 
show_always = true

[os]
format = '\[[$name](fg:#7daea3)\]'
style = "bold blue"
disabled = false

[time]
disabled = false
format = '\[[$time](fg:#d4be98)\]'
time_format = '%H:%M'
utc_time_offset = 'local'

[status]
format='-\[[$int]($style)\]'
disabled=false

[git_branch]
format = '-\[[$branch(:$remote_branch)](fg:#e78a4e)'

[git_status]
format = '([$all_status$ahead_behind](fg:#e78a4e))\]'

[python]
format = '[(\[$virtualenv\]-)](fg:#d3869b)'
