format = """
┌$time-$username-$os-$directory$status$git_branch$git_status$python 
└─> 
"""
[time]
disabled = false
format = '\[[$time](fg:#e78a4e)\]'
time_format = '%H:%M'
utc_time_offset = 'local'


[directory]
format='\[[$path](fg:#89b482)\]'
truncate_to_repo = false

[username]
format='\[[$user](fg:#d8a657)\]' 
show_always = true

[os]
format = '\[[$name](fg:#a9b665)\]'
disabled = false

[status]
format='-\[[$int]($style)\]'
success_symbol='0'
style="red"
success_style= 'fg:green'
disabled=false

[git_branch]
format = '-\[[$branch(:$remote_branch)](fg:#7daea3)'

[git_status]
format = '([$all_status$ahead_behind](fg:#7daea3))\]'

[python]
style="#d3869b"
format = '(-\[[$virtualenv]($style)\])'
